package com.one_love_international_club.enums;

public enum AuditAction {
    CREATE, UPDATE, DELETE, READ, LOGIN, LOGOUT,
    REGISTER, PASSWORD_CHANGE, PASSWORD_RESET,
    PROFILE_UPDATE, ROLE_CHANGE, PERMISSION_CHANGE,
    API_ACCESS, FILE_UPLOAD, FILE_DOWNLOAD,
    DATA_EXPORT, DATA_IMPORT, BULK_OPERATION
}
