version: "3.9"

services:
  app:
    build: docker
    ports:
      - "8080:8080"
    environment:
      PORT: ${PORT}

      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
